# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aloia CMS
tagline: >
  Aloia CMS is a CMS for developers who want to choose between "I want ultimate control over my content"
  and "Please, let the CMS do the work for me". Everything works automatically out-of-the-box,
  but you can influence every single aspect of the CMS if you so choose.
email: roelofjanelsinga@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Aloia CMS is a drop-in flat file CMS built on top of Laravel.
  You won't need to rebuild your entire application to be able to offer CMS capabilities,
  you can simply include the CMS as a library and start writing.
baseurl: ""
url: "https://aloiacms.com"
twitter_username: RJElsinga
github_username:  roelofjan-elsinga/flat-file-cms

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
markdown:     kramdown
permalink:    pretty
paginate:     4

header_pages:
  - documentation.md

collections:
  documentation:
    output: true
    order:
      - requirements.md
      - installation.md
      - plugins.md

show_social_icons: true
enable_anchorjs: true
copyright_years: 2019

defaults:
  -
    scope:
      path: ""
    values:
      author: "Roelof Jan Elsinga"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - CNAME
  - .idea/
  - node_modules
  - "package*.json"
  - "*.config.js"
